### ISSUE TITLE
Move `Line.raycast()` to `raycast()`

### ISSUE THREAD

**Issue by novialriptide** [novialriptide/pygame_geometry#58]
Something like this? This is a low priority for now, but I highly suggest this issue must be worked on before we migrate to https://github.com/pygame/pygame since `Ray != Line`
As @Starbuck5 suggested, we can do a single function that's not attached to any instance such as
```python
raycast(
    start_pos: Sequence[int, int],
    endpoint: Union[Sequence[float, float], None] = None,
    angle: Union[float, None] = None
)
# If the angle and endpoint both have values or are None, it'll raise an error.
```

The re-implementation should be pretty simple since the C implementation already exists.

**Comment by Starbuck5** [comment]
It seems to me that raycast should just be an independent function in the geometry module.

**Comment by novialriptide** [comment]
How should we design this function though? Should we take in `end_point: Sequence[float, float]`, `angle: float`, or `direction: Sequence[float, float]`?

**Comment by novialriptide** [comment]
I just got started on this issue. Expect a PR in a couple days.
