### ISSUE TITLE
Add line.collideswith() function

### ISSUE THREAD

**Issue by itzpr3d4t0r** [novialriptide/pygame_geometry#64]
We are still missing a general function for collisions. This one for line should mirror the circle one 
[here](https://github.com/novialriptide/pygame_geometry/blob/main/src_c/circle.c#L336-L366).
Lets also make an effort towards using PEP8 naming convention for functions.

**Comment by novialriptide** [comment]
The name should actually be `collideswith()` to keep consistency with other collision functions that already exist in pygame.
