### ISSUE TITLE
Polygon.update_vertex()

### ISSUE THREAD

**Issue by ScriptLineStudios** [novialriptide/pygame_geometry#89]
I think a function to update one of the vertices of a Polygon would be useful. I propose something like this.

```python
polygon = geometry.Polygon([(100, 10), (600, 600), (10, 600)])
polygon.update_vertex(0, (200, 10))
```

**Comment by itzpr3d4t0r** [comment]
I don't know if a function is the correct way of handling this, it may be sufficient to make the polygon subscriptable like we have for line:
```Python
polygon = geometry.Polygon([(100, 10), (600, 600), (10, 600)])
polygon[0] = (200, 10)
```

**Comment by ScriptLineStudios** [comment]
`

> I don't know if a function is the correct way of handling this, it may be sufficient to make the polygon subscriptable like we have for line:
> 
> ```python
> polygon = geometry.Polygon([(100, 10), (600, 600), (10, 600)])
> polygon[0] = (200, 10)
> ```

Actually yeah that makes a lot more sense.

**Comment by ScriptLineStudios** [comment]
I will try to do this
