### ISSUE TITLE
Add documentation for everything

### ISSUE THREAD

**Issue by novialriptide** [novialriptide/pygame_geometry#95]
## TO DO
- [ ] `pygame_geometry.Circle`
- [ ] `pygame_geometry.Polygon`
- [ ] `pygame_geometry.Line`

I'm not sure what we can do format-wise, leave comments below what we can do.

**Comment by itzpr3d4t0r** [comment]
We should split those tasks in 3(at least) sub-tasks each to better split work across multiple PRs and make review/additions easier. Like
- attributes
- collision
- intersection
- transform

**Comment by itzpr3d4t0r** [comment]
I guess this can be closed, we have docs now. They're still pretty much v1 but we can open other issues and PRs to modify them
